#!/bin/bash
# Angular Project Creation Commands
# Common commands for creating and initializing Angular projects

echo "=== Angular Project Creation Commands ==="
echo ""

# ===== CREATE NEW PROJECT =====
echo "1. CREATE NEW PROJECT"
echo "---"
echo "# Basic project creation (interactive)"
echo "ng new my-app"
echo ""
echo "# Skip interactive prompts"
echo "ng new my-app --routing --style=scss --skip-git"
echo ""
echo "# Without git initialization"
echo "ng new my-app --skip-git"
echo ""
echo "# Without npm install"
echo "ng new my-app --skip-install"
echo ""

# ===== PROJECT CREATION OPTIONS =====
echo "2. PROJECT CREATION OPTIONS"
echo "---"
echo "# With routing module"
echo "ng new my-app --routing"
echo ""
echo "# With specific styling"
echo "ng new my-app --style=scss"
echo "ng new my-app --style=less"
echo "ng new my-app --style=sass"
echo ""
echo "# With inline styles/templates"
echo "ng new my-app --inline-style --inline-template"
echo ""
echo "# With strict type checking"
echo "ng new my-app --strict"
echo ""
echo "# With specific package manager"
echo "ng new my-app --package-manager=npm"
echo "ng new my-app --package-manager=yarn"
echo ""
echo "# Combined example"
echo "ng new my-app --routing --style=scss --strict --skip-git"
echo ""

# ===== INITIALIZE EXISTING PROJECT =====
echo "3. INITIALIZE GIT FOR EXISTING PROJECT"
echo "---"
echo "ng new my-app --skip-git"
echo "cd my-app"
echo "git init"
echo "git add ."
echo 'git commit -m "Initial commit"'
echo ""

# ===== WORKSPACE SETUP =====
echo "4. MONOREPO/WORKSPACE SETUP"
echo "---"
echo "# Create workspace without initial app"
echo "ng new workspace --create-application=false"
echo ""
echo "# Generate applications in workspace"
echo "ng generate application admin-app"
echo "ng generate application user-app"
echo ""
echo "# Generate libraries"
echo "ng generate library shared-lib"
echo "ng generate library ui-components"
echo ""
echo "# Build specific app"
echo "ng build admin-app"
echo ""
echo "# Serve specific app"
echo "ng serve admin-app"
echo ""

# ===== NAVIGATE AND SETUP =====
echo "5. NAVIGATE AND SETUP"
echo "---"
echo "cd my-app"
echo ""
echo "# Install dependencies (if skipped)"
echo "npm install"
echo ""
echo "# Start development server"
echo "npm start"
echo "# or"
echo "ng serve"
echo ""
echo "# Server runs on http://localhost:4200"
echo ""

# ===== VERIFY PROJECT STRUCTURE =====
echo "6. VERIFY PROJECT STRUCTURE"
echo "---"
echo "# List project structure"
echo "ls -la"
echo ""
echo "# View main files"
echo "cat angular.json      # CLI configuration"
echo "cat package.json      # Dependencies"
echo "cat tsconfig.json     # TypeScript config"
echo "cat src/main.ts       # Application entry point"
echo ""

# ===== MAKE FIRST COMMIT =====
echo "7. MAKE FIRST COMMIT"
echo "---"
echo "git add ."
echo 'git commit -m "Initial Angular project setup"'
echo ""

# ===== USEFUL POST-CREATION COMMANDS =====
echo "8. USEFUL POST-CREATION COMMANDS"
echo "---"
echo "# Update Angular and dependencies"
echo "ng update @angular/cli @angular/core"
echo ""
echo "# Add routing if not already added"
echo "ng generate module app-routing --flat --module=app"
echo ""
echo "# Generate shared module"
echo "ng generate module shared"
echo ""
echo "# Create main layout components"
echo "ng generate component components/header"
echo "ng generate component components/footer"
echo "ng generate component components/navigation"
echo ""

echo "=== Project Created Successfully ==="
