#!/bin/bash
# Angular Code Generation Commands
# Common ng generate commands for scaffolding Angular code

echo "=== Angular Code Generation Commands ==="
echo ""

# ===== COMPONENTS =====
echo "1. GENERATE COMPONENTS"
echo "---"
echo "# Basic component"
echo "ng generate component components/user-list"
echo "ng g c components/user-list  # shorthand"
echo ""
echo "# Component with routing"
echo "ng generate component pages/home --route app"
echo ""
echo "# Component with specific style"
echo "ng generate component user-list --style=scss"
echo ""
echo "# Component with inline template/style"
echo "ng generate component user-list --inline-template --inline-style"
echo ""
echo "# Skip test file"
echo "ng generate component user-list --skip-spec"
echo ""
echo "# Standalone component (Angular 14+)"
echo "ng generate component user-list --standalone"
echo ""

# ===== SERVICES =====
echo "2. GENERATE SERVICES"
echo "---"
echo "# Basic service"
echo "ng generate service services/user"
echo "ng g s services/user  # shorthand"
echo ""
echo "# Service in specific module"
echo "ng generate service services/user --module=app"
echo ""
echo "# Skip test file"
echo "ng generate service services/user --skip-spec"
echo ""

# ===== MODULES =====
echo "3. GENERATE MODULES"
echo "---"
echo "# Basic module"
echo "ng generate module modules/admin"
echo "ng g m modules/admin  # shorthand"
echo ""
echo "# Module with routing"
echo "ng generate module modules/admin --routing"
echo ""
echo "# Shared module"
echo "ng generate module shared --flat"
echo ""

# ===== DIRECTIVES =====
echo "4. GENERATE DIRECTIVES"
echo "---"
echo "# Directive"
echo "ng generate directive directives/highlight"
echo "ng g d directives/highlight  # shorthand"
echo ""
echo "# Skip test file"
echo "ng generate directive directives/highlight --skip-spec"
echo ""

# ===== PIPES =====
echo "5. GENERATE PIPES"
echo "---"
echo "# Pipe"
echo "ng generate pipe pipes/custom-filter"
echo "ng g p pipes/custom-filter  # shorthand"
echo ""
echo "# Skip test file"
echo "ng generate pipe pipes/truncate --skip-spec"
echo ""

# ===== GUARDS =====
echo "6. GENERATE GUARDS"
echo "---"
echo "# Auth guard"
echo "ng generate guard guards/auth"
echo "ng g g guards/auth  # shorthand"
echo ""
echo "# Specific guard type (Angular 17+)"
echo "ng generate guard guards/auth --implements CanActivate"
echo ""

# ===== INTERCEPTORS =====
echo "7. GENERATE INTERCEPTORS"
echo "---"
echo "# HTTP interceptor"
echo "ng generate interceptor interceptors/auth"
echo "ng g i interceptors/auth  # shorthand"
echo ""
echo "# Specific interceptor type"
echo "ng generate interceptor interceptors/auth --implements HttpInterceptor"
echo ""

# ===== MODELS & INTERFACES =====
echo "8. GENERATE MODELS & INTERFACES"
echo "---"
echo "# Interface"
echo "ng generate interface models/user"
echo "ng g i models/user  # shorthand"
echo ""
echo "# Class"
echo "ng generate class models/user"
echo "ng g cl models/user  # shorthand"
echo ""
echo "# Enum"
echo "ng generate enum models/role"
echo "ng g e models/role  # shorthand"
echo ""

# ===== RESOLVERS =====
echo "9. GENERATE RESOLVERS"
echo "---"
echo "# Data resolver"
echo "ng generate resolver resolvers/user"
echo "ng g r resolvers/user  # shorthand"
echo ""

# ===== FEATURE GENERATION =====
echo "10. GENERATE FEATURE MODULES"
echo "---"
echo "# Complete feature with module, components, services"
echo "ng generate module features/dashboard --routing"
echo "ng generate component features/dashboard/pages/dashboard --module=features/dashboard"
echo "ng generate component features/dashboard/components/widget"
echo "ng generate service features/dashboard/services/dashboard"
echo ""

# ===== BATCH GENERATION =====
echo "11. BATCH GENERATION EXAMPLE"
echo "---"
echo "# Generate complete admin feature"
echo "ng generate module modules/admin --routing"
echo "ng generate component modules/admin/pages/admin-home"
echo "ng generate component modules/admin/pages/users-list"
echo "ng generate component modules/admin/pages/user-detail"
echo "ng generate service modules/admin/services/admin"
echo "ng generate service modules/admin/services/user"
echo "ng generate guard modules/admin/guards/admin"
echo ""

# ===== VERIFY GENERATION =====
echo "12. VERIFY GENERATED CODE"
echo "---"
echo "# List generated components"
echo "find src/app -name '*.component.ts' | head -10"
echo ""
echo "# List generated services"
echo "find src/app -name '*.service.ts' | head -10"
echo ""
echo "# Verify module imports"
echo "cat src/app/app.module.ts"
echo ""

# ===== USEFUL OPTIONS =====
echo "13. USEFUL GENERATION OPTIONS"
echo "---"
echo "# Skip module update (don't add to module)"
echo "ng generate component user-list --skip-import"
echo ""
echo "# Specify selector prefix"
echo "ng generate component user-list --selector=custom-users"
echo ""
echo "# Don't create folder"
echo "ng generate component user-list --flat"
echo ""
echo "# Change export location"
echo "ng generate service user --flat=false"
echo ""

echo "=== Code Generation Complete ==="
