#!/bin/bash
# Angular Build & Deployment Commands
# Commands for building, testing, and deploying Angular applications

echo "=== Angular Build & Deployment Commands ==="
echo ""

# ===== DEVELOPMENT BUILD =====
echo "1. DEVELOPMENT BUILD"
echo "---"
echo "# Start development server"
echo "ng serve"
echo "npm start"
echo ""
echo "# Serve on specific port"
echo "ng serve --port 4300"
echo ""
echo "# Serve on specific host"
echo "ng serve --host 0.0.0.0"
echo ""
echo "# Combined"
echo "ng serve --port 4300 --host 192.168.1.100"
echo ""
echo "# Build and serve"
echo "ng build --watch"
echo ""

# ===== PRODUCTION BUILD =====
echo "2. PRODUCTION BUILD"
echo "---"
echo "# Build for production"
echo "ng build --configuration production"
echo ""
echo "# Shorthand"
echo "ng build -c production"
echo ""
echo "# Output in dist/app-name/"
echo ""

# ===== BUILD OPTIONS =====
echo "3. BUILD OPTIONS"
echo "---"
echo "# Build with source maps"
echo "ng build --source-map"
echo ""
echo "# Build to specific directory"
echo "ng build --output-path=./build"
echo ""
echo "# Build with progress indicator"
echo "ng build --progress"
echo ""
echo "# Build and show stats"
echo "ng build --stats-json"
echo ""
echo "# Build with specific configuration"
echo "ng build --configuration staging"
echo ""

# ===== TESTING =====
echo "4. TESTING COMMANDS"
echo "---"
echo "# Run unit tests"
echo "ng test"
echo ""
echo "# Run tests once (no watch)"
echo "ng test --watch=false"
echo ""
echo "# Run with code coverage"
echo "ng test --code-coverage"
echo ""
echo "# Run specific test file"
echo "ng test --include='**/user.service.spec.ts'"
echo ""
echo "# Run E2E tests"
echo "ng e2e"
echo ""

# ===== LINTING =====
echo "5. LINTING COMMANDS"
echo "---"
echo "# Lint all files"
echo "ng lint"
echo ""
echo "# Lint specific file"
echo "ng lint src/app/user.service.ts"
echo ""
echo "# Fix linting issues automatically"
echo "ng lint --fix"
echo ""
echo "# Show verbose output"
echo "ng lint --verbose"
echo ""

# ===== BUNDLE ANALYSIS =====
echo "6. BUNDLE ANALYSIS"
echo "---"
echo "# Build with stats"
echo "ng build --configuration production --stats-json"
echo ""
echo "# Install webpack analyzer"
echo "npm install --save-dev webpack-bundle-analyzer"
echo ""
echo "# Analyze bundle"
echo "webpack-bundle-analyzer dist/my-app/stats.json"
echo ""
echo "# Or use source-map-explorer"
echo "npm install --save-dev source-map-explorer"
echo "source-map-explorer dist/my-app/**/*.js"
echo ""

# ===== PREVIEW PRODUCTION BUILD =====
echo "7. PREVIEW PRODUCTION BUILD"
echo "---"
echo "# Build production"
echo "ng build --configuration production"
echo ""
echo "# Install serve globally"
echo "npm install -g serve"
echo ""
echo "# Serve production build"
echo "serve dist/my-app"
echo ""
echo "# Or use Python"
echo "cd dist/my-app"
echo "python -m http.server 8000"
echo ""
echo "# Or use Node http-server"
echo "npx http-server dist/my-app"
echo ""

# ===== CACHE MANAGEMENT =====
echo "8. CACHE MANAGEMENT"
echo "---"
echo "# Clear Angular build cache"
echo "rm -rf .angular/cache"
echo ""
echo "# Clear npm cache"
echo "npm cache clean --force"
echo ""
echo "# Deep clean"
echo "rm -rf node_modules package-lock.json"
echo "npm install"
echo ""

# ===== CONFIGURATION MANAGEMENT =====
echo "9. CONFIGURATION MANAGEMENT"
echo "---"
echo "# List available configurations"
echo "ng build --help | grep configuration"
echo ""
echo "# Build with custom configuration"
echo "ng build --configuration=staging"
echo "ng build --configuration=production"
echo "ng build --configuration=development"
echo ""

# ===== DEPLOYMENT =====
echo "10. DEPLOYMENT COMMANDS"
echo "---"
echo "# Build for deployment"
echo "ng build --configuration production"
echo ""
echo "# Deploy to Vercel"
echo "npm install -g vercel"
echo "vercel"
echo ""
echo "# Deploy to Netlify"
echo "npm install -g netlify-cli"
echo "netlify deploy"
echo ""
echo "# Deploy to GitHub Pages"
echo "npm run build"
echo "npx angular-cli-ghpages --dir=dist/my-app"
echo ""
echo "# Deploy to traditional server (SCP)"
echo "scp -r dist/my-app/ user@server:/var/www/html/"
echo ""
echo "# Deploy with rsync"
echo "rsync -av dist/my-app/ user@server:/var/www/html/"
echo ""

# ===== DOCKER DEPLOYMENT =====
echo "11. DOCKER DEPLOYMENT"
echo "---"
echo "# Build Docker image"
echo "docker build -t my-angular-app ."
echo ""
echo "# Run Docker container"
echo "docker run -p 80:80 my-angular-app"
echo ""

# ===== ENVIRONMENT VARIABLES =====
echo "12. ENVIRONMENT VARIABLES"
echo "---"
echo "# Increase Node memory for large builds"
echo "export NODE_OPTIONS=--max-old-space-size=4096"
echo ""
echo "# Windows"
echo "set NODE_OPTIONS=--max-old-space-size=4096"
echo ""

# ===== TROUBLESHOOTING =====
echo "13. TROUBLESHOOTING"
echo "---"
echo "# Port already in use"
echo "ng serve --port 4300"
echo ""
echo "# Build fails - clear cache and reinstall"
echo "rm -rf node_modules package-lock.json .angular/cache"
echo "npm install"
echo "ng build"
echo ""
echo "# Memory error during build"
echo "export NODE_OPTIONS=--max-old-space-size=4096"
echo "ng build"
echo ""

# ===== UPDATE DEPENDENCIES =====
echo "14. UPDATE DEPENDENCIES"
echo "---"
echo "# Check for updates"
echo "ng update"
echo ""
echo "# Update all packages"
echo "ng update @angular/cli @angular/core"
echo ""
echo "# Update specific package"
echo "ng update @angular/core"
echo ""

echo "=== Build & Deployment Complete ==="
